# Generated by Django 5.1.6 on 2025-02-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cognom1', models.CharField(max_length=100)),
                ('cognom2', models.CharField(blank=True, max_length=100, null=True)),
                ('correu', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('student', 'Alumne'), ('teacher', 'Professor')], max_length=10)),
                ('curs', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
