# Generated by Django 5.1.6 on 2025-03-05 16:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cognom1', models.CharField(max_length=100)),
                ('cognom2', models.CharField(blank=True, max_length=100)),
                ('correu', models.EmailField(max_length=254, unique=True)),
                ('curs', models.CharField(help_text="Curs en què està matriculat l'alumne", max_length=10)),
                ('moduls', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, help_text='Llistat de mòduls matriculats', size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cognom1', models.CharField(max_length=100)),
                ('cognom2', models.CharField(blank=True, max_length=100)),
                ('correu', models.EmailField(max_length=254, unique=True)),
                ('curs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, help_text='Llistat de cursos que imparteix', size=None)),
                ('tutor', models.BooleanField(default=False)),
                ('moduls', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, help_text='Llistat de mòduls', size=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
