# Generated by Django 5.1.7 on 2025-03-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuari',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
