# Generated by Django 5.1.7 on 2025-03-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usuari_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuari',
            name='cognoms',
        ),
    ]
